
DEVKITARM=/home/nostromo/caanoodev/gcc-4.2.4-glibc-2.7-eabi/

PREFIX		:=	arm-gph-linux-gnueabi-

include $(PWD)/caanoo_rules

CFLAGS	:= -O3 -DNDEBUG -Wall -DCPP_MEMORY -DPLATFORM_$(PLATFORM) -I$(PWD)/../sources -D__LINUX_OSS__ 
#CFLAGS	:= -g -D_DEBUG -Wall -DCPP_MEMORY -DPLATFORM_$(PLATFORM) -I$(PWD)/../sources -D__LINUX_OSS__ 

CXXFLAGS:=	$(CFLAGS)

EXTENSION:= gpe

LIBS	:=  -L/c/GPH_SDK/tools/cross-eabi/arm-gph-linux-gnueabi/sys-root/ -L/c/GPH_SDK/tools/cross-eabi/arm-gph-linux-gnueabi/sys-root/lib -L/c/GPH_SDK/tools/cross-eabi/arm-gph-linux-gnueabi/sys-root/usr/lib -lSDL 
#-lpthread 


LIBDIRS	:=	$(DEKVITARM)/lib
