
include $(PWD)/osx_rules

CFLAGS  := -O3 -DCPP_MEMORY -w -I$(PWD)/../sources -I$(shell brew --prefix sdl12-compat)/include
# DEBUG BUILD (use this to debug with lldb)
#CFLAGS	:= -g -O0 -DCPP_MEMORY -Wall -I$(PWD)/../sources -I$(shell brew --prefix sdl12-compat)/include/ -D_DEBUG -DDEBUG

CXXFLAGS:= $(CFLAGS) -std=c++17

EXTENSION:= app

LIBS	:=  -lSDL

