
WTOOLPATH=c:/MinGW/bin

PREFIX := 

include $(PWD)/base_rules

CFLAGS	:= -mthreads -g -Wall $(INCLUDES) -D_DEBUG -DDEBUG -DPLATFORM_$(PLATFORM) -I$(PWD)/../sources

CXXFLAGS:= $(CFLAGS)
LDFLAGS := -L../../libs/Wsdl-mingw
LIBS     :=  -lmingw32 -lSDLmain -lSDL -mwindows   -luser32 -lgdi32 -lwinmm -ldxguid

EXTENSION:= exe
