pages:
  - frontcover.md
  - contents.md
  - introduction.md
  - getting-started.md
  - device.md
  - projects.md
  - songs.md
  - chains.md
  - phrases.md
  - instruments.md
  - grooves.md
  - tables.md
  - renders.md
  - mixer.md
  # reference
  - keypadcombos.md
  - commands.md
  - scales.md
  - midi.md
  - appendix-remoteui.md
  - theindex.md
