#ifndef _ETL_PROFILE_H_
#define _ETL_PROFILE_H_

#define ETL_TARGET_DEVICE_GENERIC
#define ETL_TARGET_OS_NONE
#define ETL_CPP11_SUPPORTED 1
#define ETL_CPP14_SUPPORTED 1
#define ETL_CPP17_SUPPORTED 1
#define ETL_CHECK_PUSH_POP

#endif
